version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: mycooldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: mycoolapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mycooldb
      SPRING_DATASOURCE_USERNAME: exampleuser
      SPRING_DATASOURCE_PASSWORD: examplepass
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: