management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: >-
          beans, caches, conditions, env, flyway, health, httptrace ,
          integrationgraph, loggers, liquibase, metrics, mappings,
          scheduletasks, sessions, shutdown, threaddump, info, auditevents,
          configprops
spring:
  profile:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      format_sql: true
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: root
      password: root
  sql:
    init:
      continue-on-error: true
server:
  port: 8080
  servlet:
    context-path: /myapp
  session:
    timeout: 5m
logging:
  level:
    org.springframework: INFO
    hibernate: TRACE
    com.springboot.demo.mycoolapp: INFO
  file: coolapp.log
  pattern:
    console: >-
      %clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint}
      %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue}
      %clr(:){red} %clr(%m){faint}%n
